Feature/EPL-529 Add hooks when process shipments
etendosoftware/etendo_core pull request #132
Opened 2023-01-24 14:17 UTC by juabaez

2023-01-25 12:30 UTC, isaiasb-etendo approved these changes

2023-01-25 12:46 UTC, smfnicolasre submitted a review, later dismissed

2023-01-26 11:07 UTC, RubenEtendo approved these changes

2023-01-26 17:09 UTC, RubenEtendo approved these changes

2023-01-26 17:11 UTC, smfnicolasre approved these changes

2023-01-27 13:06 UTC, RubenEtendo requested changes

2023-01-27 13:06 UTC, RubenEtendo commented on modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/actionHandler/AddPaymentActionHandler.java
> +//  @Override
Should these commented lines of code be deleted or are they useful? If so, then uncomment them

2023-01-27 14:54 UTC, RubenEtendo approved these changes

2023-01-27 14:55 UTC, merged