Feature EPL-544: Vulnerability found in Postgresql JDBC
etendosoftware/etendo_core pull request #154
Opened 2023-03-10 19:25 UTC by sebastianbarrozo

2023-03-10 19:30 UTC, Matias-Bernal approved these changes

2023-03-10 19:35 UTC, juabaez approved these changes

2023-03-14 18:56 UTC, valeriag-etendo approved these changes

2023-03-16 00:21 UTC, valeriag-etendo requested changes
@sebastianbarrozo The format of the commits is incorrect. It should be:
`Issue #150: <message> | EPL-554`

2023-03-16 17:58 UTC, valeriag-etendo approved these changes

2023-03-16 18:03 UTC, merged