Feature ETO-99: Add pipelines to run tests with different PG versions
etendosoftware/etendo_core pull request #156
Opened 2023-03-23 12:43 UTC by valeriag-etendo

2023-03-23 19:23 UTC, isaiasb-etendo approved these changes

2023-03-28 20:16 UTC, Matias-Bernal approved these changes

2023-03-29 12:31 UTC, isaiasb-etendo approved these changes

2023-03-29 16:53 UTC, isaiasb-etendo approved these changes

2023-03-29 19:17 UTC, Matias-Bernal approved these changes

2023-03-30 13:17 UTC, sebastianbarrozo requested changes

2023-03-30 13:17 UTC, sebastianbarrozo commented on pipelines/unittests/Jenkinsfile
> +    - name: kube-api-access-tl4l4
This volume is k8s internal , keep rsa-keys and docker-sock

2023-03-30 13:17 UTC, sebastianbarrozo commented on pipelines/unittests/Jenkinsfile
> +        - name: kube-api-access-tl4l4
This mount is k8s internal, remove it

2023-03-31 13:04 UTC, merged