Hotfix/#173 epl 591
etendosoftware/etendo_core pull request #174
Opened 2023-04-26 17:41 UTC by juabaez

2023-04-26 18:50 UTC, Matias-Bernal requested changes

2023-04-26 18:50 UTC, Matias-Bernal commented on src/com/etendoerp/sequences/SequencesGenerator.java
> +    return !sequenceOBCriteria.list().isEmpty();
idem a lo del otro PR

2023-04-27 18:26 UTC, Matias-Bernal approved these changes

2023-04-27 19:04 UTC, isaiasb-etendo approved these changes

2023-05-02 13:44 UTC, valeriag-etendo approved these changes

2023-05-02 14:02 UTC, merged