Feature EPL-327: Etendo RX Module implementation
etendosoftware/etendo_core pull request #18
Opened 2022-07-07 17:14 UTC by pabloelena

Creation of new windows to allow the user define the entities to be projected.

2022-07-08 12:47 UTC, isaiasb-etendo commented on modules_core/com.etendoerp.etendorx/src-db/database/sourcedata/AD_MODULE.xml
> +<!--BC7B2F721FD249F5A360C6AAD2A7EBF7-->  <LICENSETYPE><![CDATA[ETCL]]></LICENSETYPE>
If the module is not commercial, the license should be Apache License 2.0

2022-07-08 15:02 UTC, isaiasb-etendo approved these changes

2022-07-12 19:00 UTC, juabaez requested changes

2022-07-12 19:00 UTC, juabaez commented on modules_core/com.etendoerp.etendorx/src/com/etendoerp/etendorx/selector/ETRXSelectorFieldPropertyDataSource.java
> +    private static final String TAB_ID = "inpTableId";
change variable name to TABLE_ID

2022-07-13 12:47 UTC, valeriag-etendo approved these changes

2022-07-13 12:55 UTC, merged