Issue #188: Fix error with sequences
etendosoftware/etendo_core pull request #189
Opened 2023-06-12 19:09 UTC by EzequielNicolasRafti

EPL-668

2023-06-12 19:24 UTC, juabaez requested changes

2023-06-12 19:24 UTC, juabaez commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    if (cDocTypeID.equals("")) {
use stringUtils

2023-06-12 19:24 UTC, juabaez commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    if (AD_Client_ID.equals("0")) {
use stringUtils

2023-06-12 19:24 UTC, juabaez commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    if (cs == null || cs.razon == null || cs.razon.equals("")) {
use stringUtils

2023-06-12 19:24 UTC, juabaez commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    if (cDocTypeID.equals("")) {
use stringUtils

2023-06-12 19:24 UTC, juabaez commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    if (AD_Client_ID.equals("0")) {
use stringUtils

2023-06-12 19:24 UTC, juabaez commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    if (cs == null || cs.razon == null || cs.razon.equals("")) {
use stringUtils

2023-06-12 19:32 UTC, Gremiger requested changes

2023-06-12 19:32 UTC, Gremiger commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    if (TableName == null || TableName.length() == 0) {
As "TableName" is a String. Is it not better to use 
 `StringUtils.isBlank(TableName) ?`

2023-06-12 19:32 UTC, Gremiger commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    if (TableName == null || TableName.length() == 0) {
Use StringUtils.isBlank()   or StringUtils.isEmpty() according to the case.

2023-06-12 19:32 UTC, Gremiger commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    } catch (final ServletException e) {
Empty catch block.

2023-06-12 19:32 UTC, Gremiger commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    if (TableName == null || TableName.length() == 0) {
StringUtils

2023-06-12 19:32 UTC, Gremiger commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    } catch (final ServletException e) {
Empty catch block

2023-06-14 11:19 UTC, juabaez approved these changes

2023-06-14 12:31 UTC, Gremiger approved these changes

2023-06-16 18:34 UTC, Matias-Bernal requested changes

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +      throw new IllegalArgumentException("Utility.getDocumentNo - required parameter missing");
StringUtils.isEmpty(TableName)

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +  public String getDocumentNo(ConnectionProvider conn, VariablesSecureApp vars, String WindowNo,
vars names are in mixed case with a lowercase first letter.

https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    final String cDocTypeID = (C_DocTypeTarget_ID.equals("") ? C_DocType_ID : C_DocTypeTarget_ID);
StringUtils.isEmpty(C_DocTypeTarget_ID) ? C_DocType_ID : C_DocTypeTarget_ID

or

StringUtils.defaultIfBlank(C_DocTypeTarget_ID, C_DocType_ID)

https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#defaultIfBlank-T-T-

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +      throw new UnsupportedOperationException("Utility.getDocumentNo - Cannot add System records");
Add ad_message

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    }
Noting to do?

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +      throw new IllegalArgumentException("Utility.getDocumentNo - required parameter missing");
Add ad_message

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +  public String getDocumentNo(Connection conn, ConnectionProvider con, VariablesSecureApp vars,
vars names are in mixed case with a lowercase first letter.

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    final String cDocTypeID = (C_DocTypeTarget_ID.equals("") ? C_DocType_ID : C_DocTypeTarget_ID);
You can also do it as:

String cDocTypeID = StringUtils.defaultIfBlank(C_DocTypeTarget_ID, C_DocType_ID);

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    final String AD_Org_ID = Utility.getContext(con, vars, "AD_Org_ID", WindowNo);
vars names are in mixed case with a lowercase first letter.

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    }
Noting to do?

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +  public String getDocumentNo(ConnectionProvider conn, String AD_Client_ID, String TableName,
vars names are in mixed case with a lowercase first letter.

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +  public String getDocumentNoByOrg(ConnectionProvider conn, String AD_Client_ID, String AD_Org_ID,
vars names are in mixed case with a lowercase first letter.

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +      throw new IllegalArgumentException("Utility.getDocumentNo - required parameter missing");
Add ad_message

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +      String AD_Client_ID, String TableName, boolean updateNext) {
vars names are in mixed case with a lowercase first letter.

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +      throw new IllegalArgumentException("Utility.getDocumentNo - required parameter missing");
Add ad_message

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    if (TableName == null || TableName.length() == 0) {
StringUtils.isEmpty(TableName)

2023-06-16 18:34 UTC, Matias-Bernal commented on modules_core/com.etendoerp.legacy.advpaymentmngt/src/com/etendoerp/legacy/utilitySequence/UtilitySequenceLegacy.java
> +    }
Noting to do?

2023-06-16 18:34 UTC, Matias-Bernal commented on src/org/openbravo/erpCommon/utility/DocumentNo_data.xsql
> +        CALL legap_sequence_doc_by_org(?,?,?,?,?)
do you check it on Oracle Database?

2023-06-23 15:01 UTC, Gremiger requested changes

2023-06-26 15:17 UTC, Matias-Bernal approved these changes

2024-03-08 19:12 UTC, closed without merging