Hotfix/#121 epl 512
etendosoftware/etendo_core pull request #210
Opened 2023-08-02 11:38 UTC by LeandroCazorla15

2023-08-02 11:48 UTC, juabaez requested changes

2023-08-02 11:48 UTC, juabaez commented on src/org/openbravo/erpCommon/ad_callouts/SL_Order_Amt.java
> +        calcDiscount = priceStd.compareTo(priceActual) == 0 || priceStd.compareTo(BigDecimal.ZERO) != 0;
first the constant when compare

2023-08-04 12:20 UTC, juabaez approved these changes

2023-08-04 15:16 UTC, smfnicolasre approved these changes

2023-08-04 18:54 UTC, RubenEtendo approved these changes

2023-08-04 20:02 UTC, merged