Feature EPL-830: Modify Swagger, updating and adding parameters.
etendosoftware/etendo_core pull request #213
Opened 2023-08-15 17:27 UTC by AyelenGarcia01

2023-08-15 18:37 UTC, RomanMagnoli approved these changes

2023-08-15 18:38 UTC, Gremiger requested changes

2023-08-15 20:24 UTC, Gremiger approved these changes

2023-08-16 00:18 UTC, smfnicolasre approved these changes

2023-08-16 11:13 UTC, valenvivaldi approved these changes

2023-08-16 17:33 UTC, closed without merging