Hotfix/#222 epl 860
etendosoftware/etendo_core pull request #223
Opened 2023-09-02 00:51 UTC by jortolanosmf

2023-09-04 12:58 UTC, isaiasb-etendo commented on src/build.xml
> +    <echo>Archivos incluidos en el fileset:</echo>
Spanish?

2023-09-04 15:25 UTC, isaiasb-etendo approved these changes

2023-09-04 15:35 UTC, sebastianbarrozo requested changes

2023-09-04 15:37 UTC, sebastianbarrozo commented
Give more details about the PR in the title and description.

2023-09-05 15:23 UTC, valeg-etendo approved these changes

2023-09-05 16:06 UTC, RomanMagnoli approved these changes

2023-09-05 18:26 UTC, sebastianbarrozo approved these changes

2023-09-05 18:40 UTC, merged