Issue #232: Error when trying to insert an alert rule
etendosoftware/etendo_core pull request #244
Opened 2023-11-07 19:53 UTC by Tomas-Vesco

EPL-1066: Error when trying to insert an alert rule

2023-11-07 20:20 UTC, RomanMagnoli approved these changes

2023-11-08 11:00 UTC, valenvivaldi approved these changes

2023-11-08 14:04 UTC, Gremiger approved these changes

2023-11-16 13:09 UTC, valeg-etendo requested changes

2023-11-16 13:09 UTC, valeg-etendo commented on modules_core/org.openbravo.advpaymentmngt/src-util/buildvalidation/src/org/openbravo/advpaymentmngt/buildvalidation/WrongPaymentScheduleDetailsCheck_data.xsql
> +    <Sql><![CDATA[INSERT INTO AD_ALERTRULE (AD_ALERTRULE_ID, AD_CLIENT_ID, AD_ORG_ID,ISACTIVE, CREATED, CREATEDBY,  UPDATED, UPDATEDBY, NAME, AD_TAB_ID, FILTERCLAUSE, TYPE, SQL) VALUES (?, '0', '0',
The formatting could be improved to make the change more readable.

2023-11-16 13:09 UTC, valeg-etendo commented on modules_core/org.openbravo.advpaymentmngt/src-util/buildvalidation/src/src/org/openbravo/advpaymentmngt/buildvalidation/WrongPaymentScheduleDetailsCheckData.java
> +      "INSERT INTO AD_ALERTRULE (AD_ALERTRULE_ID, AD_CLIENT_ID, AD_ORG_ID,ISACTIVE, CREATED, CREATEDBY,  UPDATED, UPDATEDBY, NAME, AD_TAB_ID, FILTERCLAUSE, TYPE, SQL) VALUES (?, '0', '0', 'Y', now(),
The formatting could be improved to make the change more readable.

2023-12-05 13:15 UTC, valeg-etendo approved these changes

2023-12-05 18:22 UTC, merged