Issue #245: Invoice line with 0 amount remains without taxes
etendosoftware/etendo_core pull request #268
Opened 2023-12-12 17:48 UTC by Tomas-Vesco

2023-12-12 18:04 UTC, Gremiger requested changes

2023-12-12 18:04 UTC, Gremiger commented on src-db/database/model/triggers/C_INVOICELINETAX_TRG.xml
> +
Before the XML had spaces and now it has tabs, check it and try to have it unified (Only tabs or only spaces). The lines before and after the changes have only spaces

2023-12-12 18:04 UTC, Gremiger commented on src-db/database/model/triggers/C_ORDERLINETAX_TRG.xml
> +	DELETE FROM C_ORDERTAX
Before the XML had spaces and now it has tabs, check it and try to have it unified (Only tabs or only spaces). The lines before and after the changes have only spaces

2023-12-13 20:13 UTC, valeg-etendo requested changes
@Tomas-Vesco Both commits have the same message. In case they are the same, make a squash but if they are not the same, make them more descriptive.

2023-12-15 18:11 UTC, Gremiger approved these changes

2023-12-22 13:26 UTC, valeg-etendo approved these changes

2023-12-22 13:41 UTC, merged