Issue #281: AverageAlgorithm class can be improved by showing the product.getName() on the OBException
etendosoftware/etendo_core pull request #296
Opened 2024-01-22 18:39 UTC by tomyrodeghiero

EPL-1196: Include product.getName() in OBException

2024-01-22 18:54 UTC, RomanMagnoli approved these changes

2024-01-22 20:01 UTC, valeg-etendo requested changes

2024-01-22 20:01 UTC, valeg-etendo commented on src/org/openbravo/costing/AverageAlgorithm.java
> +      String productInfo = String.format("%s (Search Key: %s)", product.getName(), product.getSearchKey());
The message for 'Search Key' must be used, otherwise the message will not be translated in case the environment is in English.

2024-01-22 20:05 UTC, valeg-etendo requested changes

2024-01-22 20:05 UTC, valeg-etendo commented on src/org/openbravo/costing/AverageAlgorithm.java
> +      String productInfo = String.format("%s (Search Key: %s)", product.getName(), product.getSearchKey());
The message should be constructed as it was done in CostingUtils.java

`+ ", @Product@: " + product.getName() + ", @ACCS_VALUE@: " + product.getSearchKey()`

2024-01-23 13:13 UTC, valeg-etendo approved these changes

2024-01-23 14:21 UTC, merged