Hotfix/#312 epl 1299
etendosoftware/etendo_core pull request #316
Opened 2024-02-22 14:30 UTC by tomyrodeghiero

2024-02-22 15:15 UTC, Gremiger commented
Hi, should this changes be done in the advanced general ledger from "com.etendoerp.financial.reports.advanced"? @valeg-etendo @isaiasb-etendo @RubenEtendo @EzequielNicolasRafti

2024-02-22 16:51 UTC, tomyrodeghiero commented
> Hi, should this changes be done also in the advanced general ledger from "com.etendoerp.financial.reports.advanced"? @valeg-etendo @isaiasb-etendo @RubenEtendo @EzequielNicolasRafti

Hi @Gremiger!

Yes, I have it assigned and will be addressing it in this separate task: [EE-839](https://etendoproject.atlassian.net/browse/EE-839). Thank you for pointing it out

2024-02-23 11:18 UTC, valeg-etendo requested changes

2024-02-23 11:18 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportGeneralLedgerJournal_data.xsql
> +  <Sql>
@tomyrodeghiero fix indentation

2024-02-23 11:18 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/info/AccountElementValue_data.xsql
> +              AND C.ELEMENTLEVEL = 'S'
@tomyrodeghiero Is this indentation correct?

2024-02-26 18:23 UTC, merged