Issue #286: Fix invoice blocking when completing
etendosoftware/etendo_core pull request #332
Opened 2024-03-03 21:49 UTC by jortolanosmf

2024-03-03 22:09 UTC, Matias-Bernal requested changes

2024-03-03 22:09 UTC, Matias-Bernal commented on modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/ProcessInvoices.java
> +                if (invoice.isProcessNow() && "CO".equals(documentAction)){
StringUtils

2024-03-03 22:09 UTC, Matias-Bernal commented on modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/ProcessInvoices.java
> +                Boolean lockedRecord=false;
for this case, you must be use primitive boolean.

2024-03-03 22:09 UTC, Matias-Bernal commented on modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/ProcessInvoices.java
>                  if (message.getType().equals("Error")) {
StringUtils

2024-03-03 22:09 UTC, Matias-Bernal commented on modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/ProcessInvoices.java
> +                if (!message.getType().equals("Error") && lockedRecord){
StringUtils instead string.equals, also you can improved this if condition evaluation using the evaluation of lockedRecord first as primitive boolean.

2024-03-04 13:13 UTC, Gremiger commented on modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/ProcessInvoices.java
> +                    OBDal.getInstance().flush();
This flush is needed inside the for-loop?
 If possible, extract the flush outside of the loop

2024-03-05 17:07 UTC, Matias-Bernal commented on modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/ProcessInvoices.java
> +                    OBDal.getInstance().save(invoice);
You removed the flush line but you don't add it after the loop execution.

2024-03-05 22:07 UTC, closed without merging