Issue #369: Correct error handling when deleting accounting data
etendosoftware/etendo_core pull request #370
Opened 2024-04-23 14:46 UTC by RubenEtendo

EPL-1452

2024-04-23 17:44 UTC, Matias-Bernal approved these changes

2024-04-23 19:23 UTC, RomanMagnoli approved these changes

2024-04-25 11:34 UTC, valenvivaldi approved these changes

2024-04-25 14:43 UTC, Gremiger approved these changes

2024-04-25 17:54 UTC, valeg-etendo requested changes

2024-04-25 17:54 UTC, valeg-etendo commented on src-test/src/org/openbravo/test/StandaloneTestSuite.java
> +
@facumoyanosmf Delete this blank line

2024-04-25 17:54 UTC, valeg-etendo commented on src-test/src/org/openbravo/test/StandaloneTestSuite.java
> +    // Count and Discount a Document without Doc base type configured and get an error.
@facumoyanosmf Add Jira task ID.

2024-04-25 17:54 UTC, valeg-etendo commented on src-test/src/org/openbravo/test/accounting/PostedNoDocConfigTest.java
> + */
@facumoyanosmf Add Jira task ID.

2024-04-26 13:50 UTC, valeg-etendo approved these changes

2024-04-26 13:51 UTC, merged