Issue #368: Change button behavior and add a loader.
etendosoftware/etendo_core pull request #384
Opened 2024-05-06 16:23 UTC by RomanMagnoli

Add disable value after clicking the OK button. Also, a reformat was applied.

2024-05-06 18:03 UTC, Gremiger approved these changes

2024-05-07 12:03 UTC, valeg-etendo requested changes

2024-05-07 12:03 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_forms/UpdateReferenceData.html
> +                                    <img id="loadGif" style="display: none;" src="https://demo.etendo.cloud/etendo/web/org.openbravo.userinterface.smartclient/openbravo/skins/Default/org.openbravo.cl
maybe 

```suggestion
                                    <img id="loadGif" style="display: none;" src="../../../../../modules_core/org.openbravo.client.application/web/org.openbravo.userinterface.smartclient/openbravo/skins/Default/org.openbravo.client.application/images/system/windowLoading.gif"/>
```

2024-05-08 15:29 UTC, RomanMagnoli commented on src/org/openbravo/erpCommon/ad_forms/UpdateReferenceData.html
> +                                    <img id="loadGif" style="display: none;" src="https://demo.etendo.cloud/etendo/web/org.openbravo.userinterface.smartclient/openbravo/skins/Default/org.openbravo.cl
Fixed

2024-05-08 19:00 UTC, valeg-etendo approved these changes

2024-05-08 20:08 UTC, Matias-Bernal approved these changes

2024-05-08 20:22 UTC, merged