Issue #306>: added the fix to allow the custom accounting while posting internal consumption document
etendosoftware/etendo_core pull request #401
Opened 2024-05-21 13:36 UTC by Amar-Etendo

Issue #306>: added the fix to allow the custom accounting while posting internal consumption document
EPL-1238

2024-05-21 14:00 UTC, facumoyanosmf commented
> Issue #306>: added the fix to allow the custom accounting while posting internal consumption document EPL-1238

@Amar-Etendo The commit name should be Issue #306: ..., not Issue #306>: .... On the other hand, the characters of each message must not exceed 70 characters. [Methodology for repository management](https://etendoproject.atlassian.net/wiki/spaces/ERP/pages/2795077633/Methodology+for+repository+management+with+GIT)

2024-05-21 14:06 UTC, RubenEtendo commented
@Amar-Etendo Check the sonar comment, you have a code smell in this Pull Request

Other than that, the code looks fine, good job!

2024-05-21 14:42 UTC, valeg-etendo approved these changes

2024-05-21 14:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_forms/DocInternalConsumption.java
> +    if(!StringUtils.isEmpty(strClassname)) {
```suggestion
    if (!StringUtils.isEmpty(strClassname)) {
```

2024-05-21 14:51 UTC, RomanMagnoli commented
As the sonar Analysis said, the method has high cognitive complexity. This should be fixed.
![Selección_951](https://github.com/etendosoftware/etendo_core/assets/136735078/372f06a7-0536-4fed-802d-c6ec433566f2)

2024-05-21 15:16 UTC, RubenEtendo commented
> > Issue #306>: added the fix to allow the custom accounting while posting internal consumption document EPL-1238
> 
> @Amar-Etendo The commit name should be Issue #306: ..., not Issue #306>: .... On the other hand, the characters of each message must not exceed 70 characters. [Methodology for repository management](https://etendoproject.atlassian.net/wiki/spaces/ERP/pages/2795077633/Methodology+for+repository+management+with+GIT)

@Amar-Etendo remember what @facumoyanosmf told you about the commit message. The new commit also has the '>' in it

2024-05-22 15:43 UTC, Matias-Bernal commented on src/org/openbravo/erpCommon/ad_forms/DocInternalConsumption.java
> +        data1 = getInternalConsumptionWarehouse(conn, docLine);
`DocInternalConsumptionData[] data1 = getInternalConsumptionWarehouse(conn, docLine);`

2024-05-22 15:54 UTC, Matias-Bernal requested changes
Check determineCostCurrency method to improve it.

2024-05-22 21:51 UTC, Matias-Bernal approved these changes

2024-05-23 13:56 UTC, RomanMagnoli approved these changes

2024-05-24 19:01 UTC, merged