Issue #351: Add exception in report valuation stock
etendosoftware/etendo_core pull request #477
Opened 2024-09-23 16:21 UTC by Agustin-Calderon

ETP-51

2024-09-26 17:19 UTC, valeg-etendo approved these changes

2024-09-27 12:59 UTC, RomanMagnoli approved these changes

2024-09-27 13:36 UTC, jortolanosmf approved these changes

2024-09-27 14:01 UTC, Matias-Bernal requested changes

2024-09-27 14:01 UTC, Matias-Bernal commented on src-test/src/org/openbravo/test/stockValuationReport/ReportValuationStockTestUtil.java
> +    params.put("C_Currency_ID", "100");
OBBaseTest.DOLLAR_ID

2024-09-27 14:01 UTC, Matias-Bernal commented on src-test/src/org/openbravo/test/stockValuationReport/ReportValuationStockTestUtil.java
> +    params.put("Date", "2024-09-24");
Maybe this can be a method parameter.

2024-09-27 16:03 UTC, Matias-Bernal approved these changes

2024-09-27 18:51 UTC, merged