Feature ETP-768: Change <option> HTML tag improving a patch.
etendosoftware/etendo_core pull request #537
Opened 2024-11-21 01:09 UTC by Matias-Bernal

ETP-768: Applied a patch to improve <option> HTML tag in <selection> tag to improve the code and prepare it to future upgrade to remove <span> tags into <options> and avoid a Chrome warning.

2024-11-21 18:42 UTC, valeg-etendo requested changes

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportAnnualCertification.html
> +				  <div id="reportAD_ORGID"/>
@Matias-Bernal fix indentation

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportAssetDepreciationSchedule.html
> +                  <select  name="inpOrg" id="inpOrg" class="ComboKey Combo_TwoCells_width" required="true">
@Matias-Bernal fix indentation

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportAssetDepreciationSchedule.html
> +                  <select  name="inpcAssetCategoryId" id="inpcAssetCategoryId" class="Combo Combo_TwoCells_width">
@Matias-Bernal fix indentation

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportAssetDepreciationSchedule.html
> +                  <select  name="inpcAcctSchemaId" id="inpcAcctSchemaId" class="Combo Combo_TwoCells_width">
@Matias-Bernal fix indentation

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportSalesOrderInvoicedJasper.html
> +		              <td class="TitleCell"><span class="LabelText">Product</span></td>
@Matias-Bernal fix indentation

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportPurchaseDimensionalAnalysesFilterJR.html
> +                      <option value=""/>
@Matias-Bernal fix indentation

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportProjectBuildingSiteJR.html
> +                </td>
@Matias-Bernal fix indentation

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportOrderNotInvoiceFilterJR.html
> +		              <td class="TitleCell"><span class="LabelText">Details</span></td>
@Matias-Bernal fix indentation

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportInvoicesJR.html
> +                <div id="reportC_Currency_ID"/>
@Matias-Bernal fix indentation

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportInvoiceVendorFilterJR.html
>                    	<select name="inpCurrencyId" id="inpCurrencyId" class="ComboKey Combo_OneCell_width" required="true">
@Matias-Bernal fix indentation

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportInvoiceVendorDimensionalAnalysesFilterJR.html
>                    	  <select name="inpCurrencyId" id="inpCurrencyId" class="ComboKey Combo_OneCell_width" required="true">
@Matias-Bernal fix indentation

2024-11-21 18:42 UTC, valeg-etendo commented on src/org/openbravo/erpCommon/ad_reports/ReportExpense.html
> +				        <tr>
@Matias-Bernal fix indentation

2024-11-22 16:45 UTC, RomanMagnoli approved these changes

2024-11-25 14:02 UTC, valeg-etendo approved these changes

2024-11-25 14:10 UTC, valeg-etendo approved these changes

2024-11-28 16:58 UTC, merged