Feature ETP-870: Add tests for jobs defaults & ReportValuationStock
etendosoftware/etendo_core pull request #559
Opened 2024-12-17 15:36 UTC by Emi-Polliotti

2024-12-17 19:24 UTC, valeg-etendo requested changes

2024-12-17 19:24 UTC, valeg-etendo commented on src-test/src/com/etendoerp/reportvaluationstock/handler/CostingRuleUtilsTest.java
> +      assertNotNull("El resultado no debería ser null", result);
@Emi-Polliotti message should be in english

2024-12-17 19:24 UTC, valeg-etendo commented on src-test/src/com/etendoerp/reportvaluationstock/handler/CostingRuleUtilsTest.java
> +      assertEquals("El resultado debería ser el CostingRule esperado", expectedRule, result);
@Emi-Polliotti message should be in english

2024-12-17 19:24 UTC, valeg-etendo commented on src-test/src/com/etendoerp/reportvaluationstock/handler/ReportValuationStockParametersTest.java
> +  private static final String TEST_ORG_ID = "testOrgId";
@Emi-Polliotti I see many constants that could be in a generic utils.

2024-12-17 19:24 UTC, valeg-etendo commented on src-test/src/com/smf/jobs/defaults/ProcessOrdersDefaultsTest.java
> +    when(mockFieldProvider.getField("ID")).thenReturn("CO");
@Emi-Polliotti "CO" and "DR" 
convert to constant and pass to Utils

2024-12-18 12:07 UTC, isaiasb-etendo approved these changes

2024-12-18 12:52 UTC, valeg-etendo approved these changes

2024-12-18 14:27 UTC, ivanrobledofutit approved these changes

2024-12-18 15:25 UTC, merged