Feature/epl 405
etendosoftware/etendo_core pull request #81
Opened 2022-09-19 15:13 UTC by juabaez

2022-09-19 21:40 UTC, Matias-Bernal commented on modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/ProcessOrderUtil.java
> +                if (msg != null && "Error".equals(msg.getType())) {
StringUtils.equals("Error",msg.getType())

2022-09-19 21:42 UTC, Matias-Bernal commented on modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/ProcessOrderUtil.java
> +                if (msg != null && "Error".equals(msg.getType())) {
Also, you may append all hook's messages in a single.

2022-09-19 21:43 UTC, Matias-Bernal commented on modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/ProcessOrderUtil.java
> +            if ("CO".equals(strdocaction)) {
StringUtils.equals

2022-09-19 21:43 UTC, Matias-Bernal commented on modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/ProcessOrderUtil.java
> +            OBContext.setAdminMode(true);
It's must be in try statement

2022-09-19 21:45 UTC, Matias-Bernal commented on modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/ProcessOrderUtil.java
> +            OBContext.setAdminMode();
It's must be in try statement

2022-09-19 21:46 UTC, Matias-Bernal commented on modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/ProcessOrderUtil.java
> +                if (msg != null && "Error".equals(msg.getType())) {
StringUtils.equals("Error",msg.getType())

2022-09-19 21:46 UTC, Matias-Bernal commented on modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/ProcessOrderUtil.java
> +                if (msg != null && "Error".equals(msg.getType())) {
Also, you may append all hook's messages in a single.

2022-09-19 21:47 UTC, Matias-Bernal commented on modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/ProcessOrders.java
> +        if (message.getType().equals("Error")) {
StringUtils.equals("Error",msg.getType())

2022-09-19 21:47 UTC, Matias-Bernal commented on modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/ProcessOrders.java
> +        if (message.getMessage().isBlank()) {
StringUtils.isBlank

2022-09-19 21:50 UTC, Matias-Bernal requested changes
Fix, at least, setAdminMode errors

2022-09-20 14:50 UTC, Matias-Bernal approved these changes

2022-09-20 16:09 UTC, Matias-Bernal approved these changes

2022-09-22 16:29 UTC, valeriag-etendo approved these changes

2022-09-22 18:56 UTC, merged