Feature EPL-391: Search params needs an order column
etendosoftware/etendo_core pull request #89
Opened 2022-09-29 18:30 UTC by sebastianbarrozo

2022-09-29 18:47 UTC, juabaez requested changes

2022-09-29 18:47 UTC, juabaez commented on modules_core/com.etendoerp.etendorx/src-db/database/sourcedata/AD_COLUMN.xml
> +<!--773096CF83C84101BD90332349021C2D-->  <ISMANDATORY><![CDATA[N]]></ISMANDATORY>
the ad_element are missing

2022-09-30 15:09 UTC, isaiasb-etendo approved these changes

2022-09-30 22:11 UTC, Matias-Bernal approved these changes

2022-10-05 12:35 UTC, valeriag-etendo approved these changes

2022-10-05 13:54 UTC, merged